name: PythonHomeworkEnvironment
channels:
  - defaults
dependencies:
  - ca-certificates=2018.03.07=0
  - certifi=2018.10.15=py37_0
  - flake8=3.6.0=py37_0
  - libedit=3.1.20170329=h6b74fdf_2
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - mccabe=0.6.1=py37_1
  - ncurses=6.1=hf484d3e_0
  - openssl=1.0.2p=h14c3975_0
  - pip=18.1=py37_0
  - pycodestyle=2.4.0=py37_0
  - pyflakes=2.0.0=py37_0
  - python=3.7.0=h6e4f718_3
  - readline=7.0=h7b6447c_5
  - setuptools=40.6.2=py37_0
  - sqlite=3.25.3=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - wheel=0.32.3=py37_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=ha838bed_2
prefix: /home/yaliangchang/miniconda3/envs/PythonHomeworkEnvironment

