name: PythonHomeworkEnvironment
channels:
  - defaults
dependencies:
  - blas=1.0=mkl
  - ca-certificates=2018.03.07=0
  - certifi=2018.10.15=py37_0
  - flake8=3.6.0=py37_0
  - freetype=2.9.1=h8a8886c_1
  - intel-openmp=2019.1=144
  - jpeg=9b=h024ee3a_2
  - libedit=3.1.20170329=h6b74fdf_2
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.35=hbc83047_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libtiff=4.0.9=he85c1e1_2
  - mccabe=0.6.1=py37_1
  - mkl=2018.0.3=1
  - mkl_fft=1.0.6=py37h7dd41cf_0
  - mkl_random=1.0.1=py37h4414c95_1
  - ncurses=6.1=hf484d3e_0
  - numpy=1.15.4=py37h1d66e8a_0
  - numpy-base=1.15.4=py37h81de0dd_0
  - olefile=0.46=py37_0
  - openssl=1.0.2p=h14c3975_0
  - pillow=5.3.0=py37h34e0f95_0
  - pip=18.1=py37_0
  - pycodestyle=2.4.0=py37_0
  - pyflakes=2.0.0=py37_0
  - python=3.7.0=h6e4f718_3
  - readline=7.0=h7b6447c_5
  - setuptools=40.6.2=py37_0
  - sqlite=3.25.3=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - wheel=0.32.3=py37_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=ha838bed_2
prefix: /home/master/07/yaliangchang/miniconda3/envs/PythonHomeworkEnvironment

